services:
  expense_tracker:
    container_name: expense_tracker
    build:
      context: .
      dockerfile: ./docker/local/server/Dockerfile
    volumes:
        - ./server:/server
        - /server/node_modules
    env_file:
        - ./.env
    expose: 
      - ${PORT}
    ports:
      - 8080:${PORT}
    networks:
        - expense_tracker_db_net
        - local-nginx-net

    command: npm run dev

  expence_client:
    container_name: expense_client
    build:
      context: .
      dockerfile: ./docker/local/client/Dockerfile
    volumes:
      - ./client:/client
      -  /client/node_modules
    ports:
      - 5173:5173
    networks:
      - local-nginx-net
    command: npm run dev
    



  expense_db:
    container_name: expense_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - expense_tracker_db_net


networks:
  local-nginx-net:
    external: true
  expense_tracker_db_net:


volumes:
  pg-data:







