services:
  expense_tracker:
    container_name: expense_tracker
    build:
      context: .
      dockerfile: ./docker/local/server/Dockerfile
    volumes:
        - ./server:/server
        - /server/node_modules
    ports:
      - 8080:8080
    networks:
        - expense_tracker_db_net

    command: npm run dev


  expense_db:
    container_name: expense_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - expense_tracker_db_net


networks:
  expense_tracker_db_net:


volumes:
  pg-data:







