CREATE TABLE IF NOT EXISTS users (
id BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
email varchar(100) NOT NULL UNIQUE,
password varchar(200) NOT NULL ,
created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
