CREATE TABLE payments(
id BIGINT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
name varchar(100) NOT NULL,
payed_due_date TIMESTAMP WITH TIME ZONE NOT NULL,
amount NUMERIC NOT NULL,
user_id BIGINT NOT NULL,
is_payed BOOLEAN NOT NULL,
created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
UNIQUE(payed_due_date, amount),
CONSTRAINT fk_users FOREIGN KEY (user_id) REFERENCES users(id)
);
