CREATE SCHEMA IF NOT EXISTS expense_schema;

CREATE TABLE IF NOT EXISTS expense_schema.users_schema(
id BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
file_name varchar(50) NOT NULL UNIQUE
);


INSERT INTO expense_schema.users_schema(file_name) 
VALUES('0001_init.sql') ON CONFLICT DO NOTHING;


